apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend-svc
spec:
  type: LoadBalancer 
  selector:
    service: frontend
  ports:
  - name: "8100"
    protocol: TCP
    port: 80
    targetPort: 80
  
  