language: generic

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend ./udagram-refactoring-project-solution/udagram-frontend
  - docker tag udagram-frontend sijoonlee/udagram-frontend:latest
  - docker build -t endpoint-user ./udagram-refactoring-project-solution/udagram-api-user
  - docker tag endpoint-user sijoonlee/endpoint-user:latest
  - docker build -t endpoint-feed ./udagram-refactoring-project-solution/udagram-api-feed
  - docker tag endpoint-feed sijoonlee/endpoint-feed:latest
  - docker build -t reverse-proxy ./udagram-refactoring-project-solution/udagram-deployment/docker
  - docker tag reverse-proxy sijoonlee/reverse-proxy:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sijoonlee/udagram-frontend
  - docker push sijoonlee/endpoint-user
  - docker push sijoonlee/endpoint-feed
  - docker push sijoonlee/reverse-proxy
