apiVersion: v1
kind: Service
metadata:
  labels:
    service: endpoint-feed
  name: endpoint-feed-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: endpoint-feed
