language: minimal

services:
    - docker

# Pre-testing installs
install:
    - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
    - echo "no tests"

script:
    - docker --version # print the version for logging
    - docker build -t simple-reverse-proxy .
    - docker tag simple-reverse-proxy sijoonlee/simple-reverse-proxy:latest

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push sijoonlee/simple-reverse-proxy

    